### ISSUE TITLE
Can't assign Buttons Settings for ELF files within a FHDB Internal HDD setup in wLE

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#22] opened 2018-09-25 22:50 UTC
@sp193 -- We have a bug report at PS2-HOME: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=6346

Where the user wants to setup his wLE page to adjust buttons to quickly launch ELF files that are exist inside his INTERNAL HDD using FHDB.  It seems when he tries to save his BUTTON settings, he gets this error: **“Failed To Save LAUNCHELF.CNF”**

Example:
(assign the SQUARE button to launch the following ELF file within this path)
`hdd0:/__sysconf/FMCB/PS2Restart.ELF`

Can you tell us if this is a common bug with FHDB not allowing to do this with wLE or simply a bug in wLE?

Or can you browse the help topic to see what he is doing wrong?

He eventually was able to set up wLE by editing the `LAUNCHELF.CNF` file, by adding the links to the ELF files, by using NOTEPAD++ (-- **FYI**: earlier in that thread, he reported he couldn't do that, since he was using Windows Notepad -- and we all know that utility causes issues with encoding formats.  But once he switched to NOTEPAD++ he was able to workaround this bug.)

But yet, if he tries to adjust his buttons settings within the wLE settings page, he can't.  The only links he can setup are the functions found within wLE's `/MISC` folder.

**NOTE**: this doesn't happen to wLE when using it with FMCB, so we assume it maybe a FHDB and wLE conflict?

**Comment by sp193** [comment] 2018-10-20 14:43
Fixed in aec8e35.

The issue was caused by LaunchELF generating an unsupported path for its files, on the pfs device. Loading of settings works the first time because there was code added for loading the HDD modules & mounting the partition.

However, subsequent saving & loading of the configuration files will fail because the partition may not be mounted and it lacks the code for doing so. Plus the path on the pfs device contains no information on which partition to mount.

The solution was to generate a path that LaunchELF supports.

There was also this other problem with the display setting not binding if LaunchELF is booted from the HDD unit, due to the real CNF file only being loaded after the UI (and hence the GS) has been initialized. The solution was to load the CNF in its usual local, before initializing the GS.
Previously, doing that would crash the PS2 because the loadHddModules() function tries to draw some status text on the UI. I inhibited that action to make things work.

**Closed by sp193** 2018-10-20 14:43 UTC
